name: Bug report
description: Report something that is broken or not working as expected.
title: "Bug: "
body:
  - type: textarea
    id: summary
    attributes:
      label: What happened?
      description: Describe the issue and what you expected to see instead.
      placeholder: "The YouTube embed shows an error on Safari..."
    validations:
      required: true
  - type: input
    id: page
    attributes:
      label: Page URL
      description: Paste the page where the issue appears.
      placeholder: "https://streamn.dad/"
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device and browser
      description: Example: iPhone 14 / Safari 17 or Windows 11 / Chrome 121.
      placeholder: "MacBook Pro (M1) / Chrome 121"
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List the steps so I can reproduce it.
      placeholder: "1. Open the homepage..."
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (optional)
      description: Drag and drop images here if helpful.
    validations:
      required: false
