name: Feature or idea
description: Suggest a new section, tool, or improvement.
title: "Idea: "
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like to see?
      description: Describe the idea and the outcome you want.
      placeholder: "Add a section that..."
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Additional details
      description: Share links, references, or examples if you have them.
    validations:
      required: false
